[build]
  base = "frontend/my-app"    # Adjust if your Next.js app is in a different location
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://groshmebeta-05487aa160b2.herokuapp.com"
  NEXT_PUBLIC_SUPABASE_URL = "https://bvgnlxznztqggtqswovg.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2Z25seHpuenRxZ2d0cXN3b3ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5MDI1ODIsImV4cCI6MjA1MDQ3ODU4Mn0.I8alzEBJYt_D1PDZHvuyZzLzlAEANTGkeR3IRyp1gCc"
  REACT_APP_API_URL = "https://groshme-beta-c6285c415769.herokuapp.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"